spring:
  application:
    name: oauth-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:oauth2Service
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
      enabled: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 32fb32a76e19cccdc4bd
            client-secret: efb5be8d3c98929aac687618a2d85ff62ffd8ffb

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

  logging:
    pattern.level:%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

